/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface RpAmbulanceWlList {
    }
}
declare global {
    interface HTMLRpAmbulanceWlListElement extends Components.RpAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLRpAmbulanceWlListElement: {
        prototype: HTMLRpAmbulanceWlListElement;
        new (): HTMLRpAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "rp-ambulance-wl-list": HTMLRpAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface RpAmbulanceWlList {
    }
    interface IntrinsicElements {
        "rp-ambulance-wl-list": RpAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "rp-ambulance-wl-list": LocalJSX.RpAmbulanceWlList & JSXBase.HTMLAttributes<HTMLRpAmbulanceWlListElement>;
        }
    }
}
